USE PROYECTO_FINAL; -- USAMOS BASE DE DATOS DEL PROYECTO-FINAL 

SELECT * FROM PARTIDO 
ORDER BY ID_PARTIDO DESC; 

INSERT INTO PARTIDO(fecha, id_estadio, id_equipo1, id_equipo2, id_arbitro, goles_equipo1, goles_equipo2)
VALUES ('2023-01-10', 7, 1, 2, 1, 2,2);

DELETE FROM PARTIDO
WHERE ID_PARTIDO = 1902;

SELECT * FROM LOG_AUDITORIA_INS_PARTIDO;
SELECT * FROM LOG_AUDITORIA_DEL_PARTIDO;

select * from jugador
order by id_jugador desc;

INSERT INTO JUGADOR(nombre, edad, id_posicion, id_pierna_habil, id_equipo, id_pais) 
VALUES ('prueba', 22, 1, 1, 1, 1);

DELETE FROM JUGADOR
WHERE ID_JUGADOR = 1101;

SELECT * FROM LOG_AUDITORIA_INS_JUGADOR;
SELECT * FROM LOG_AUDITORIA_DEL_JUGADOR;

