USE PROYECTO_FINAL;

SELECT * FROM PARTIDO
ORDER BY ID_PARTIDO DESC;

INSERT INTO PARTIDO(fecha, id_estadio, id_equipo1, id_equipo2, id_arbitro, goles_equipo1, goles_equipo2)
VALUES ('2023-01-10', 7, 1, 2, 1, 2,2);

DELETE FROM PARTIDO
WHERE ID_PARTIDO = 1902;


SELECT * FROM LOG_AUDITORIA_INS_PARTIDO;
SELECT * FROM LOG_AUDITORIA_DEL_PARTIDO;


