DELIMITER $$
CREATE TRIGGER TRG_PARTIDO_AI AFTER INSERT ON PROYECTO_FINAL.PARTIDO 
FOR EACH ROW
BEGIN 
INSERT INTO LOG_AUDITORIA_INS_PARTIDO(NOMBRE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_INS)
VALUES ('INSERT', 'PARTIDO', CURRENT_USER(), NOW());
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_PARTIDO_BD BEFORE DELETE ON PROYECTO_FINAL.PARTIDO 
FOR EACH ROW
BEGIN 
INSERT INTO LOG_AUDITORIA_DEL_PARTIDO(NOMBRE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_DEL)
VALUES ('DELETE', 'PARTIDO', CURRENT_USER(), NOW());
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_JUGADOR_AI AFTER INSERT ON PROYECTO_FINAL.JUGADOR
FOR EACH ROW
BEGIN 
INSERT INTO LOG_AUDITORIA_INS_JUGADOR(NOMBRE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_INS)
VALUES ('INSERT', 'JUGADOR', CURRENT_USER(), NOW());
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_JUGADOR_BD BEFORE DELETE ON PROYECTO_FINAL.JUGADOR
FOR EACH ROW
BEGIN 
INSERT INTO LOG_AUDITORIA_DEL_JUGADOR(NOMBRE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_DEL)
VALUES ('DELETE', 'JUGADOR', CURRENT_USER(), NOW());
END$$
DELIMITER ;




